on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: repo checkout
      uses: actions/checkout@v4
    - name: node setup
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: install
      run: |-
        npm i
        npm install --global @angular/cli
    - name: build
      run: ng build
    - name: upload
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: 'ftp.pein-gera.de'
        user: 'root'
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist/mk8-builder"
        remoteDir: "/ftp/root/vhosts/mk8builder.pein-gera.de"
